---
rootdir: "/var/languishes"

hostname: "languishes.net"
listen_port: 8080
nginx_version: "1.0.8"
www_redirect: true

jenkins_on: true
jenkins_jobdir: "/Users/ckoenig/.jenkins/languishes"
jenkins_port: 8585
---
